// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1767888694);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.startup.homepage_override.buildID", "20240418052210");
user_pref("browser.startup.homepage_override.mstone", "115.10.0");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20251120161723");
user_pref("extensions.lastAppVersion", "7.0.30");
user_pref("extensions.lastPlatformVersion", "115.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"zotero-ner-author-normalizer@marcinmilkowski.pl\":\"b87d065c-edab-42d3-8f35-a09edd8e8a14\"}");
user_pref("extensions.zotero.dataDir", "/Users/marcinmilkowski/Zotero");
user_pref("extensions.zotero.debug.console", true);
user_pref("extensions.zotero.debug.logging", true);
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.lastViewedFolder", "L1");
user_pref("extensions.zotero.panes.abstract.open", true);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.prefVersion", 13);
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroMacWordIntegration.lastAttemptedVersion", "7.0.6.SOURCE");
user_pref("extensions.zoteroOpenOfficeIntegration.lastAttemptedVersion", "7.0.5.SOURCE");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("intl.accept_languages", "pl, en-US, en");
