# Zotero test profile - generated by test harness
# Disable automatic updates and sync to speed up tests
app.update.enabled=false
app.update.autoUpdateEnabled=false
app.update.showUpdateHistory=false

# Disable sync
services.sync.enabled=false
services.sync.server.enabled=false

# Disable automatic backups
zotero.autoBackup.interval=0
zotero.backup.enabled=false

# Disable automatic syncing
zotero.sync.autoSync=false

# Speed up UI
nglayout.initialpaint.delay=0
content.notify.interval=100

# Reduce logging noise
javascript.options.strict=true
javascript.options.strict.debug=false
