// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.autoUpdateEnabled", false);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1769465409);
user_pref("app.update.lastUpdateTime.background-update-timer", 1769465409);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1769465409);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1769465378);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.startup.homepage_override.buildID", "20251201132345");
user_pref("browser.startup.homepage_override.mstone", "140.6.0");
user_pref("content.notify.interval", 100);
user_pref("devtools.console.stdout.chrome", true);
user_pref("devtools.console.stdout.content", true);
user_pref("extensions.autoDisableScopes", 0);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.enabledAddons", "zotero-ner-author-normalizer@marcinmilkowski.pl:1.0.0");
user_pref("extensions.enabledScopes", 15);
user_pref("extensions.installDistroAddons", true);
user_pref("extensions.lastAppBuildId", "20260121202211");
user_pref("extensions.lastAppVersion", "8.0");
user_pref("extensions.lastPlatformVersion", "140.6.0");
user_pref("extensions.logging.enabled", true);
user_pref("extensions.pendingOperations", false);
user_pref("extensions.sideloadScopes", 15);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"zotero-ner-author-normalizer@marcinmilkowski.pl\":\"51a2dd24-e7e1-4482-b5bf-bba3c59f33d2\"}");
user_pref("extensions.zotero-ner.testMode", true);
user_pref("extensions.zotero-ner.testResultsPath", "/mnt/d/git/zotero-ner/tests/zotero-framework/profile/zotero-ner-test-results.json");
user_pref("extensions.zotero.dataDir", "/mnt/d/git/zotero-ner/tests/zotero-framework/profile/zotero-data");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.httpServer.port", 35647);
user_pref("extensions.zotero.lastViewedFolder", "L1");
user_pref("extensions.zotero.panes.abstract.open", true);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.note-info.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.prefVersion", 19);
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zoteroOpenOfficeIntegration.lastAttemptedVersion", "7.0.6.SOURCE");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.webrender.enabled", false);
user_pref("gfx.webrender.force-disabled", true);
user_pref("intl.accept_languages", "en-US, en");
user_pref("layers.acceleration.disabled", true);
user_pref("nglayout.initialpaint.delay", 0);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("services.sync.enabled", false);
user_pref("services.sync.server.enabled", false);
user_pref("zotero.autoBackup.interval", 0);
user_pref("zotero.backup.enabled", false);
user_pref("zotero.debug.log", true);
user_pref("zotero.debug.log.timestamp", true);
